### ISSUE TITLE
My first bug!

### ISSUE THREAD

**Issue by leonormes** [russormes/a2p#8]
On new-pupil-form branch I am getting uninitialized constant Pupil::Grouping error when I destroy a record. The method is on pupils controller but it is being all funny about it. I'm tired and I don't know what to do.
Any ideas?

**Comment by russormes** [comment]
I'll take a look, but at a guess it doesn't like the capitalization and/or Grouping is not a field in pupils. It is treating Pupil::Grouping as a constant, a variable that has been set and is not changed, but we don't have a constant called Grouping in the pupil class. 

What is it meant to be doing?

**Comment by russormes** [comment]
Ok, so this is an issue with the realtionship in the pupil model. 

Go to app/model/pupil.rb and comment out the group relationships as we haven't set them up yet. 

Then, go delete a pupil and see if you know why you get the error it now sends you. Then fix it! I'll give you a gold star.
